version: '3.8'

services:
  web:
    build: .
    container_name: django_plate_detection
    working_dir: /app
    #ports:
    #  - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=example.com
      - CSRF_TRUSTED_ORIGINS=https://example.com
