# Generated by Django 4.2.17 on 2025-03-02 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_carhistory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carhistory",
            name="created_date",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2025, 3, 2, 18, 25, 12, 101684, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="carhistory",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
