# Generated by Django 4.2.17 on 2025-03-30 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_carhistory_usage_time_alter_carhistory_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carhistory",
            name="created_date",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2025, 3, 30, 2, 54, 5, 491221, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
