# Generated by Django 4.2.17 on 2025-03-30 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_carhistory_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carhistory",
            name="created_date",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2025, 3, 30, 2, 57, 36, 908596, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
