# Generated by Django 4.2.17 on 2025-03-02 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_carhistory_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="carhistory",
            name="vehicle_rgb",
            field=models.CharField(max_length=10, default=""),
        ),
    ]
