# Generated by Django 4.2.17 on 2025-03-02 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_carhistory_add_vehicle_rgb"),
    ]

    operations = [
        migrations.AddField(
            model_name="carhistory",
            name="fee",
            field=models.FloatField(default=12),
        ),
    ]
