# Generated by Django 4.2.17 on 2025-04-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_carhistory_add_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carhistory",
            name="created_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carhistory",
            name="fee",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carhistory",
            name="vehicle_rgb",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="carhistory",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("car", "Auto"),
                    ("mot", "Moto"),
                    ("bus", "Autobus"),
                    ("tru", "Truck"),
                    ("oth", "Otro"),
                ],
                default="car",
                max_length=3,
            ),
        ),
    ]
